version: '3'

services:
  fftcg_postgres_db:
    image: postgres:10.6
    environment:
      - POSTGRES_DB=fftcg_postgres_db
    ports:
      - '0.0.0.0:5432:5432'
  message-db:
    image: ethangarofolo/message-db:1.1.6
    ports:
      - '0.0.0.0:5433:5432'
